// Generated by CoffeeScript 1.9.2
(function() {
  $(function() {
    var hello;
    return hello = function() {
      console.log("hello");
      return console.log("hello");
    };
  });

}).call(this);

//# sourceMappingURL=hypedyn.js.map
